### ISSUE TITLE
Configuring incomplete, errors occurred!

### ISSUE THREAD

**Issue by Adwait1997** [ignitionrobotics/ign-plugin#50] opened 2021-04-01 08:39 UTC
Actually, this is not a bug or an issue with the software but a general issue. While building my plugins using CMake on Ubuntu 18.04, the console threw this error given below. 

```
CMake Error at CMakeLists.txt:10 (find_package):
  By not providing "Findcatkin.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "catkin", but
  CMake did not find one.

  Could not find a package configuration file provided by "catkin" with any
  of the following names:

    catkinConfig.cmake
    catkin-config.cmake

  Add the installation prefix of "catkin" to CMAKE_PREFIX_PATH or set
  "catkin_DIR" to a directory containing one of the above files.  If "catkin"
  provides a separate development package or SDK, be sure it has been
  installed.


Configuring incomplete, errors occurred!
```
I have implemented the source and header files for my plugin. I am not able to find info about how to generate **CMakelIsts.txt** file and **.so** for my plugin. In particular, I not able to generate the **.so** file. Any help is appreciated. Thanks,

**Comment by chapulina** [comment] 2021-04-01 16:51
> this is not a bug or an issue with the software but a general issue.

Hi @Adwait1997 , we ask that such questions be directed at https://answers.gazebosim.org.

It looks like you may be trying to use ROS 1, with catkin? This is most likely an issue with sourcing your ROS 1 installation, and not really related to Ignition Plugin.

I'll close this ticket because it's not a bug in Ignition, let's continue this conversation at Gazebo Answers :wink:

**Closed by chapulina** 2021-04-01 16:51 UTC
